version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.4.3
    ports:
      - 6200:9200
      - 6300:9300
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
  kibana:
    image: kibana:6.4.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200